project: 
  type: website
  render: 
    - "*.qmd"
  output-dir: docs

from: markdown+emoji

website: 
  title: "Bioestadística en R"
  image: icon1.png
  favicon: icon1.png
  open-graph: true
  repo-url: https://github.com/mmorenozam/biohack_progR
  navbar:
    logo: icon1.png
    title: false
    left: 
      - href: index.qmd
        text: Inicio
      - href: recursos.qmd
      - text: Módulos
        menu:
          - text: "Módulo 1"
            href: https://mmorenozam.github.io/biohack-modulo1/
            target: "_blank"
          - text: "Módulo 2"
            href: https://mmorenozam.github.io/biohack-modulo2/
            target: "_blank"
          - text: "Módulo 3"
            href: https://mmorenozam.github.io/biohack-modulo3/
            target: "_blank"
          - text: "Módulo 4"
            href: https://mmorenozam.github.io/biohack-modulo4/
            target: "_blank"
          - text: "Módulo 5"
            href: https://mmorenozam.github.io/biohack-modulo5/
          #   target: "_blank"
          # - text: "Módulo 6"
          #   href: https://mmorenozam.github.io/biohack-modulo6/
          #   target: "_blank"
          # - text: "Módulo 7"
          #   href: https://mmorenozam.github.io/biohack-modulo7/
          #   target: "_blank"
          # - text: "Módulo 8"
          #   href: https://mmorenozam.github.io/biohack-modulo8/
          #   target: "_blank"
      - text: Ejercicios
        menu:
          - text: "Demo"
            href: ejercicios_demo.qmd
          - text: "Ejercicios Módulo 1"
            href: ejercicios_m1.qmd
          - text: "Ejercicios Módulo 3"
            href: ejercicios_m3.qmd
          - text: "Ejercicios Módulo 4"
            href: ejercicios_m4.qmd
          - text: "Ejercicios Módulo 5"
            href: ejercicios_m5.qmd
          - text: "Ejercicios Módulo 7"
            href: ejercicios_m7.qmd
      - href: final.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    toc-location: left
    toc-title: Contenido
    code-copy: true
    code-overflow: wrap
