---
title: "Ejercicios Módulo 1"
format: 
  live-html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    toc-location: left
    toc-title: Contenido
    code-copy: true
    code-overflow: wrap
filters:
  - webr-teachr
  - quiz-teachr
engine: knitr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}


## Ejercicios 1.1

**1. Los creadores de R fueron Gentleman e Ihaka de la Universidad de Auckland**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**2. `5 * 5 * 5` es equivalente a `5 ^ 3`**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**3. Una lista es un arreglo que admite datos de una sola clase únicamente**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**4. Queremos comparar si `x` es igual a `5`, es la siguiente expresión correcta? `x = 5`**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**5. La función `data.frame` nos permite crear manualmente tablas de datos**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**6. Al crear un objeto de esta forma: `1_cuenta = 12` R lo crea sin error alguno**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**7. Si dejo un espacio en el nombre de un objeto, R me devuelve un error**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**8. El comando `install.libraries` me permite instalar librerías**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**9. En la expresión genérica `mean(x, . . .)` los puntos representan argumentos**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**10. Es la siguiente expresión correcta: `z -> c(1, 2, 3)`**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

## Ejercicios 1.2

Dado el siguiente objeto:


```{webr}
#| autorun: false
ev_1 <- list(tabla_de_datos = data.frame(columna_1 = c(0.2, 2.5, 3.14, 4.15, 5.55),
                                         columna_2 = c("A", "B", "C", "D", "E"),
                                         columna_3 = c("1985-10-14", "2021-12-25", "2023-01-01", "1999-05-06", "1900-01-02")),
             vector_ejemplo = c(F, T, F, T, F),
             escalar_ejemplo = 100)
```

**1. Es el elemento `vector_ejemplo` conformado por valores:**

:::{.quiz-singlechoice}
- [x] [Lógicos]{hint="o"}
- [ ] [Caracteres]{hint="x"}
- [ ] [Fechas]{hint="x"}
- [ ] [Numéricos]{hint="x"}
:::

**2. Para acceder a la tercera fila de la primera columna del elemento `tabla_de_datos`, ¿Cuál(es) de las siguientes líneas de código es(son) la(s) correcta(s)?**

```r
a) ev_1$tabla_de_datos[[1]]
b) ev_1$tabla_de_datos[1, 3]
c) ev_1[[1]][3,1]
d) ev_1$tabla_de_datos$columna_2[3]
e) ev_1[[2]][3,1]
f) ev_1$tabla_de_datos$columna_1[3]
```

:::{.quiz-multichoice}
- [ ] [a)]{hint="x"}
- [ ] [b)]{hint="x"}
- [x] [c)]{hint="o"}
- [ ] [d)]{hint="x"}
- [ ] [e)]{hint="x"}
- [x] [f)]{hint="o"}
:::

**3. Deseo concatenar `escalar_ejemplo` con `vector_ejemplo` (en ese orden) en un elemento adicional del objeto `ev_1` de nombre `conc_ejemplo`, ¿Cuál de las siguientes líneas de código es la correcta?**

```r
a) ev_1[[4]] <- ev_1[[2]] + ev_1[[3]]
b) ev_1$conc_ejemplo <- c(ev_1[[3]],ev_1[[2]])
c) ev_1$conc_ejemplo <- c(ev_1$vector_escalar + ev_1$ejemplo_escalar)
```

:::{.quiz-singlechoice}
- [ ] [a)]{hint="x"}
- [x] [b)]{hint="o"}
- [ ] [c)]{hint="x"}
:::

**4. Deseo reemplazar el cuarto elemento de `columna_2` en la `tabla_de_datos` por la letra "E", ¿Cuál sería una solución?**


:::: {.panel-tabset}

## Ejercicio

```{webr}
#| setup: true
#| exercise: ex_14
ev_1 <- list(tabla_de_datos = data.frame(columna_1 = c(0.2, 2.5, 3.14, 4.15, 5.55),
                                         columna_2 = c("A", "B", "C", "D", "E"),
                                         columna_3 = c("1985-10-14", "2021-12-25", "2023-01-01", "1999-05-06", "1900-01-02")),
             vector_ejemplo = c(F, T, F, T, F),
             escalar_ejemplo = 100)
```

```{webr}
#| exercise: ex_14
```

## Hints

::: { .hint exercise="ex_14"}
Una forma de acceder al cuarto elemento de `columna_2` en `tabla_de_datos` es:

```r
ev_1$tabla_de_datos$columna_2[4]
```
:::

## Solución

::: { .solution exercise="ex_14" }
`ev_1$tabla_de_dates$columna_2[4] <- "E"`
:::

:::

**5. Supongamos que para un determinado análisis con `tabla_de_datos`, la `columna_2` corresponde a mi factor. En este factor mi nivel de referencia es “E”. ¿Cómo especifico en R que este sea el caso?**

:::: {.panel-tabset}

## Ejercicio
```{webr}
#| setup: true
#| exercise: ex_15
ev_1 <- list(tabla_de_datos = data.frame(columna_1 = c(0.2, 2.5, 3.14, 4.15, 5.55),
                                         columna_2 = c("A", "B", "C", "D", "E"),
                                         columna_3 = c("1985-10-14", "2021-12-25", "2023-01-01", "1999-05-06", "1900-01-02")),
             vector_ejemplo = c(F, T, F, T, F),
             escalar_ejemplo = 100)
```


```{webr}
#| exercise: ex_15
```

## Hints

::: { .hint exercise="ex_15"}
Un ejemplo de código para establecer los niveles de un factor está disponible en las diapositivas
:::

## Solución

::: { .solution exercise="ex_15" }
`ev_1$tabla_de_dates$columna_2 <- relevel(as.factor(ev_1$tabla_de_dates$columna_2, ref = "E")` 
:::

:::

## Ejercicios 1.3

**1. El coeficiente de variación es adimensional**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**2. La media poblacional se aproxima a la media muestral con una corrección**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**3. La desviación estándar muestral es un estimador de la poblacional después de una corrección**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**4. La moda es igual al valor medio de una distribución**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**5. El primer cuartil corresponde al 50% de probabilidad de una distribución**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**6. Usando la variable `disp` de `mtcars`, calcula la media aritmética, la desviación estándar, la varianza, el tercer cuartil y el coeficiente de variación**



```{webr}
#| setup: true
#| exercise: ex_16
mtcars <- mtcars

```


```{webr}
#| exercise: ex_16
```