---
title: "Ejercicios Módulo 3"
format: 
  live-html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    toc-location: left
    toc-title: Contenido
    code-copy: true
    code-overflow: wrap
filters:
  - webr-teachr
  - quiz-teachr
webr:
  pagkages: ["ggplot2", "dplyr", "tidyr"]
engine: knitr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

::: {.callout-note}
## Nota
En los siguientes ejercicios se usan `{ggplot2}`, `{dplyr}` y `{tidyr}` que están precargados en la página. No es necesario que invoques las librerías.
:::

## Ejercicios 3.1

**1. El operador de cascada de base de R es `|>`**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**2. Este es un buen nombre para un objeto en R: `conteo semanal`**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**3. Cuando digo que una tabla está en formato largo, puedo decir que es rectangular**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**4. `Z` es una función, `Y` es un objeto. Con la expresión `Y(Z)` estoy evaluando `Y` en función de `Z`**

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

**5. La tabla msleep del paquete `{ggplot2}` tiene 83 filas y 11 columnas**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**6. Estas expresiones dan el mismo resultado**

```r
msleep %>% 
  filter(order == "Primates" | sleep_total >= 10)

msleep %>% 
  filter(order == "Primates", sleep_total >= 10)
```

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

```{webr}
#| setup: true
#| exercise:
#|   - ex_a6
#|   - ex_a7
#|   - ex_a8
#|   - ex_a9
#|   - ex_a10
library(ggplot2)
library(dplyr)
```

```{webr}
#| exercise: ex_a6
# Puedes copiar y pegar el código aquí directamente. 
```


**7. Estas expresión filtra la tabla `iris` excluyendo la categoría `virginica` de la columna `Species`**

```r
iris %>% 
  filter(Species != "virginica")
```

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

```{webr}
#| exercise: ex_a7
# Puedes copiar y pegar el código aquí directamente. 
```

**8. Deseo calcular la suma de `Petal.Width` por `Species` de la tabla `iris`. ¿Es correcta la siguiente expresión?**

```r
iris %>% 
  filter(Species) %>%
  summarize(suma = sum())
```

:::{.quiz-singlechoice}
- [ ] [Verdadero]{hint="x"}
- [x] [Falso]{hint="o"}
:::

```{webr}
#| exercise: ex_a8
# Puedes copiar y pegar el código aquí directamente. 
```

**9. ¿Cómo harías para que la tabla `iris` se vea de la siguiente manera?**

```r
	   largo.sepal ancho.sepal largo.petalo ancho.petalo  especies
1            5.1         3.5          1.4          0.2    setosa
2            4.9         3.0          1.4          0.2    setosa
3            4.7         3.2          1.3          0.2    setosa
4            4.6         3.1          1.5          0.2    setosa
5            5.0         3.6          1.4          0.2    setosa
```


:::: {.panel-tabset}

## Ejercicio

```{webr}
#| exercise: ex_a9
```

## Hints

::: { .hint exercise="ex_a9"}
Para cambiar el nombre y el orden de las columnas, puedes usar la función `select` de `{dplyr}`.
:::

## Solución

::: { .solution exercise="ex_a9" }
```r
iris %>%
  select(largo.sepal = Sepal.Length, ancho.sepal = Sepal.Width,
         largo.petalo = Petal.Length, ancho.petalo = Petal.Width,
         especies = Species)
```
:::

:::



**10. Usando la tabla de datos `msleep` de la libreía `{ggplot2}`, crea una tabla con los estadísticos conteo, media aritmética, mediana, desviación estándar y coeficiente de variación agrupadas por la variable `vore` de la variable `sleep_total` (un fragmento de código guía es provisto, reemplaza los espacios vacíos de la manera más conveniente).**



:::: {.panel-tabset}

## Ejercicio



```{webr}
#| exercise: ex_a10
msleep |>
  ________(vore) |>
  summarise(_________)
```

## Hints

::: { .hint exercise="ex_a10"}
Usa la función `group_by` de `{dplyr}` para agrupar por una (o más) variable (s)
:::

## Solución

::: { .solution exercise="ex_a9" }
```r
msleep |>
  filter(!is.na(vore)) %>% # para filtrar valores perdidos en la variable vore
  group_by(vore) |>
  summarise(conteo = n(), media_aritmetica = mean(sleep_total, na.rm = T),
            mediana = median(sleep_total, na.rm = T),
            desv_est = sd(sleep_total, na.rm = T),
            coef_var = desv_est / media_aritmetica * 100)
```
:::

:::

## Ejercicios 3.2

Las siguientes preguntas pueden tener más de una respuesta correcta.

**1. ¿Por qué debemos cambiar el backslash (`\`) por slash (`/`) en R?**                          

:::{.quiz-multichoice}
- [ ] [No es necesario]{hint="x"}
- [x] [El backslash puede provocar errores al ser usado para cargar caracteres especiales]{hint="o"}
- [x] [Solo es necesario cambiarlo en sistemas operativos de Windows]{hint="o"}
:::

**2.  En la función `write.csv`, si el argumento `row.names` no es seteado como `F` lo que sucede es**

:::{.quiz-singlechoice}
- [x] [El archivo .csv creado contendrá una columna extra indicando el número de fila]{hint="o"}
- [ ] [El separador de columnas será el punto y coma en lugar de la coma]{hint="x"}
- [ ] [No pasa nada]{hint="x"}
:::

**3.  `mtcars`, es una tabla de R base cuya disposición es rectangular**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**Considera el siguiente código para responder las siguientes preguntas**

```{webr}
#| setup: true
#| exercise:
#|   - ex_b4
library(dplyr)
library(tidyr)
```


```{webr}
#| exercise: ex_b4
tabla_cars <- mtcars
head(tabla_cars)
tabla_cars$marca <- row.names(tabla_cars)
tabla_cars %>% 
  pivot_longer(-c("marca"), 
               names_to = "variable", 
               values_to = "valores")
```

**3.  En la línea 1 estamos creando una copia de `mtcars`**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::

**4.  En la línea 3 estamos**

:::{.quiz-multichoice}
- [ ] [Cambiando los nombres de las columnas]{hint="x"}
- [x] [Extrayendo los nombres de las filas]{hint="o"}
- [x] [Creando una nueva variable con los nombres de las marcas de autos]{hint="o"}
:::

**4.  En las líneas 4 a 7 estamos**

:::{.quiz-singlechoice}
- [ ] [Transformando de formato largo a ancho]{hint="x"}
- [x] [Transformando de formato ancho a largo]{hint="o"}
- [ ] [Preparando la tabla para exportar]{hint="x"}
:::

**5.  La expresión `-c("marca")` significa**

:::{.quiz-singlechoice}
- [ ] [Que estamos borrando la columna "marca" de `tabla_cars`]{hint="x"}
- [x] [Que excluya "marca" del pivot]{hint="o"}
- [ ] [Ninguna de las anteriores]{hint="x"}
:::

**6.  Podemos reemplazar `-c("marca")` por simplemente `- marca`**

:::{.quiz-singlechoice}
- [x] [Verdadero]{hint="o"}
- [ ] [Falso]{hint="x"}
:::