---
title: "Trabajo final"
---

::: {.callout-important}
**Lee detenidamente las siguientes instrucciones antes de llevar a cabo el trabajo final.**
:::

## Generalidades

Independientemente de la opción que escoja el estudiante, el trabajo final deberá ser presentado de la siguiente manera:

1.    En forma de un archivo .zip conteniendo el proyecto de RStudio con todos los scripts usados para renderizar el trabajo final. **No hace falta adjuntar los datos usados para el análisis**.

2.    El archivo final renderizado puede ser presentado en formatos .pdf, .docx o .html

3.    El plazo final para la entrega del trabajo a mi correo electrónico (mmorenozambrano@gmail.com) es el **30 de Noviembre, 23H59 hora de Ecuador**.


## Opciones de trabajo final

Para aprobar el curso, el estudiante tendrá la posibilidad de optar entre las siguientes opciones:

**Opción 1:**

Presentación de un reporte estadístico con datos del estudiante o citando la fuente de los mismos. La decisión de las metodologías estadísticas es completamente libre.


**Opción 2:**

Presentación de un reporte estadístico con datos que proporciono a continuación. El estudiante deberá seguir las instrucciones de metodologías estadísticas a usar.

## Datos para la opción 2

Deberás usar la tabla de datos `community-health-evaluation-dataset`, para cargarla en tu sesión de R, usa el siguiente código

```{r, echo=T, eval=F}
git_url <- "https://raw.githubusercontent.com/mmorenozam/biohack-website/refs/heads/main/data/community_health_evaluation_dataset.csv"

df_health <- read.csv(git_url)
```

Esta tabla comprende datos cuyo gol es el de evaluar servicios de salud comunitarios y su calidad de atención. Cada fila representa información de un paciente único. Las variables son:

`Participant.ID`: identificador único de cada paciente

`Age`: edad del participante.

`Gender`: género ("M": masculino, "F": femenino).

`SES`: estado socioeconómico en escala del 1 al 4.

`Service.Type`: tipo de servicio de salud accedido por el participante.

`Visit.Frequency`: frecuencia de las visitas al doctor

`Step.Frequency..steps.min.`: media del número de pasos tomados por minuto.

`Stride.Length..m.`: media de la longitud de un paso, medida en metros.

`Joint.Angle....`: media del ángulo durante el movimiento, medida en grados.

`EMG.Activity`: nivel de la actividad muscular medida por electromiografía.

`Patient.Satisfaction..1.10.`: nivel de satisfacción del participante, medido en una escal del 1 al 10.

`Quality.of.Life.Score`: medida de la calidad de vida del participante entre 50 y 100

Para trabajar con estos datos, es necesario que pienses y formules hipótesis de investigación podrían servir como buenos indicadores de la calidad de los servicios sanitarios. 

El análisis de datos deberá incluir al menos:

1.    Aplicación de ANOVA de una vía
2.    Aplicación de ANOVA de dos vías con interacción
3.    Modelamiento de una regresión múltiple
4.    Aplicación de análisis de componentes principales

En caso de cualquier duda, siéntete libre de contactarme.