---
title: "Recursos"
---

## Clases grabadas

**09.05.2025:** video disponible [aquí](https://1drv.ms/v/c/93e2169fba83ef57/EX65r0EHI2BLngzyFnKJDH8BMvE5n-5g6IqPRJouyxy1Ww?e=0pyUf0){target="_blank"}

**12.04.2025:** Video disponible [aquí](https://1drv.ms/v/c/93e2169fba83ef57/EbHspLrqP8ZJh7lIkPt61oIBbNurAUvHnWePP84zeDEhFA?e=W0opXy){target="_blank"}


**24.04.2025:** Video disponible [aquí](https://1drv.ms/v/c/93e2169fba83ef57/EeZO1JzSmDFNu61ktiKFKIsBhjdnznMHNf8up1ig9SgeoQ?e=KkTnUp){target="_blank"}

**26.04.2025:** Video disponible [aquí](https://1drv.ms/v/c/93e2169fba83ef57/Ef9fARD8tvFJmN1sb3b7IjUBTz8ItgBjBOUyAZ_7CByLEQ?e=0X4438){target="_blank"}

## Tablas de datos extras (usadas en las diapositivas)

| Nombre      | Descripción                                                                                                                                                  |
|-------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| rotXLS.xlsx | Datos históricos de casos de rotavirus y variables ambientales de la ciudad de Berlin                                                                        |
| titatic.csv | Datos de sobrevivientes del Titanic en varios niveles de agregación (ejemplo, por género)                                                                    |
| touchon.csv | Datos de depredadores de la rana arbórea de ojos rojos (investigación del [Prof. Justin C. Touchon](https://www.jstor.org/stable/23436298){target="_blank"}) |

Se encuentran disponibles [**AQUI**](https://drive.google.com/file/d/1hy542F5j9OsucWlr8m_R9OaX4lRdDTc1/view?usp=drive_link){target="_blank"}



## Recursos extras

### Libros (gratis)

[Learning Statistics with R](https://learningstatisticswithr.com/){target="_blank"} de Danielle Navarro: excelente libro para comenzar el viaje de aprendizaje de R. Explica conceptos estadísticos de una manera sencilla y evitando complicadas fórmulas tanto como puede.

[Modern Statistics with R](https://modernstatisticswithr.com/){target="_blank"} de Måns Thulin: es un ebook que abarca a mayor profundidad aspectos de operaciones con bases de datos y modelos estadísticos más complejos que los que cubrimos en el curso.

[R for Data Science](https://r4ds.hadley.nz/){target="_blank"} de Hadley Wickham, Mine Çetinkaya-Rundel y Garrett Grolemund: es un excelente recurso para llevar a cabo modelamiento de datos desde los principios más básicos hasta la implementación de flujos de trabajo para producción. Está bastante focalizado en el uso del `tidyverse`.

[RStudio para Estadística Descriptiva en Ciencias Sociales](https://bookdown.org/gboccardo/manual-ED-UCH/) de Giorgio Boccardo Bosoni y Felipe Ruiz Bruzzone: es un ebook que contiene buena información en español sobre R. Al menos para la transformación de objetos y conducción de estadísticos descriptivos.

### Sitios web

[StackOverflow](https://stackoverflow.com/){target="_blank"}

[towards data science](https://towardsdatascience.com/){target="_blank"}

[STHDA](http://www.sthda.com/english/){target="_blank"}
